/**
 * Placeholders "blur" (LQIP) de baja resolución generados a partir de las fotos
 * de `public/`. Se usan con `<Image placeholder="blur" blurDataURL={...} />` para
 * mostrar una versión difuminada mientras carga la imagen real: mejora el LCP
 * percibido y evita el flash/salto de layout.
 */
export const BLUR = {
  principal:
    "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAATABADASIAAhEBAxEB/8QAFwAAAwEAAAAAAAAAAAAAAAAAAAIEBf/EACIQAAIBBAIBBQAAAAAAAAAAAAECAwAEERITITFBUVJhcf/EABUBAQEAAAAAAAAAAAAAAAAAAAIB/8QAGBEBAQADAAAAAAAAAAAAAAAAAAECA0H/2gAMAwEAAhEDEQA/AIpjE8yrPsJACQijJK/ftTiWTLQ29uqvpsjMfI/KmgZrSXnZeSaYYz8a0pYI2teWPYzeWdWwWHrQh5SQSgcSHAyFPdJas2g7ooqnt4//2Q==",
  retrato:
    "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAWABADASIAAhEBAxEB/8QAGAAAAgMAAAAAAAAAAAAAAAAAAAQCBQb/xAAkEAACAQQBAwUBAAAAAAAAAAABAwIABAUREiExURMyYZGxwf/EABUBAQEAAAAAAAAAAAAAAAAAAAEC/8QAGREBAQEAAwAAAAAAAAAAAAAAAQACEjFh/9oADAMBAAIRAxEAPwBvJZJ9s9VpbcF8oAmZHYnxVjjLxj7KMnaLBsSIGt/Oqz2eeF5JDljkBDhLf8+6cxl6IXBQfbMjr1J7VI1OTj7J5SxJWp5nv1AenioWsJKkpnLbBIQH7RRRnqVb/9k=",
  sesion:
    "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAALABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAgUG/8QAIhAAAgEDAwUBAAAAAAAAAAAAAQIDAAQREjFBEyGBkaGx/8QAFAEBAAAAAAAAAAAAAAAAAAAAAf/EABYRAQEBAAAAAAAAAAAAAAAAAAABEf/aAAwDAQACEQMRAD8AAnuJGlUrhCgKqBkcfaazN1kwWVcEMuwbjJHqs7cXU0kio0jaQowNuKoQyubcyFjr0Hv5x+UYbX//2Q==",
} as const;
